### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kumicoo** [Quantity-4/xiv-plugins-repo#1]
Somehow, something is wrong. Your provided repo link does not exist. Is this a cancelled plugin?

**Comment by Quantity-4** [comment]
The prototype was pre-apiX (and broke around the patch cycle that you raised this issue). Since then I have not had the time to check or work on the prototype especially as apiX was coming with DT launch.

I'll be fixing and improving on the existing code once Dalamud launches apiX officially, now that DT has launched.
